DROP TABLE IF EXISTS movies CASCADE;
DROP TABLE IF EXISTS lead_actresses;

CREATE TABLE movies (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    director TEXT NOT NULL,
    year INTEGER NOT NULL
);

CREATE TABLE lead_actresses (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    movie_id BIGINT REFERENCES movies(id)
)